server:
  port: 8086

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://localhost:5432/sparta_logistics?currentSchema=notification_db}
    username: ${DB_USERNAME:sparta}
    password: ${DB_PASSWORD:sparta1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: notification_db
    show-sql: false
    open-in-view: false
