server:
  port: 8000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_ISSUER_URI}/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-auth
              uri: lb://user-service
              predicates:
                - Path=/api/v1/auth/**
            - id: user-service-users
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
            - id: hub-service
              uri: lb://hub-service
              predicates:
                - Path=/api/v1/hubs/**
            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/api/v1/companies/**,/api/v1/products/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**
            - id: shipment-service
              uri: lb://shipment-service
              predicates:
                - Path=/api/v1/shipments/**,/api/v1/delivery-managers/**
            - id: ai-slack-service
              uri: lb://ai-slack-service
              predicates:
                - Path=/api/v1/ai-slack/**
